# Generated by Django 3.2.25 on 2024-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='inter',
            field=models.CharField(default=5, max_length=24, verbose_name='아이디어 관심도'),
        ),
        migrations.AddField(
            model_name='post',
            name='tool',
            field=models.CharField(default='python', max_length=24, verbose_name='예상 개발 툴'),
        ),
    ]
