# Generated by Django 3.2.25 on 2024-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240717_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.CharField(default='', max_length=100, verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inter',
            field=models.CharField(default='', max_length=24, verbose_name='아이디어 관심도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y%m%d', verbose_name='이미지'),
        ),
    ]
