# Generated by Django 5.0.7 on 2024-07-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_created_date_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='좋아요'),
        ),
    ]
